In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_excel(r'C:\Users\User\My ML Models\RegressionandLasso-master\Linear Regression\Home Price Prediction - Multi Variance\Home Price.xlsx')

In [3]:
df.head()

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

# Here we have missing value, so we go with median and handle nan value

In [4]:
df.bedroom.median()

3.5

In [5]:
#To convert float into int
import math          
median_bedroom = math.floor(df.bedroom.median())
median_bedroom

3

In [6]:
#Filling NaN value
df.bedroom = df.bedroom.fillna(median_bedroom)

In [7]:
df.bedroom
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [8]:
#independent feature and Dependent feature
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [9]:
#Train our model
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,y)

LinearRegression()

In [10]:
lin_reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [11]:
lin_reg.intercept_

383724.9999999998

In [12]:
lin_reg.predict([[3000,3,40]])

array([444400.])

In [13]:
lin_reg.predict([[2500,4,5]])

array([588625.])